import React, { useState, useEffect } from 'react';
import { Download, FileSpreadsheet, Calendar, CheckCircle2, ShieldAlert, Rocket, Globe2, Sparkles, FolderArchive } from 'lucide-react';

export default function ExportsTab() {
  const [archive, setArchive] = useState([]);
  const [loading, setLoading] = useState(true);
  const [todayStr, setTodayStr] = useState(new Date().toISOString().split('T')[0]);

  const fetchArchive = async () => {
    try {
      const [archiveRes, statusRes] = await Promise.all([
        fetch('/api/reports/archive'),
        fetch('/api/research/status')
      ]);
      const archiveData = await archiveRes.json();
      const statusData = await statusRes.json();
      setArchive(archiveData);
      if (statusData.todayDate) {
        setTodayStr(statusData.todayDate);
      }
    } catch (err) {
      console.error('Error fetching report archive:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchArchive();
  }, []);

  const handleDownload = (url) => {
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', '');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      {/* Top Banner */}
      <div className="zyoin-card" style={{ padding: '1.25rem', borderLeft: '4px solid #16a34a', display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: '1rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <div style={{ padding: '0.75rem', borderRadius: '12px', background: '#f0fdf4', color: '#16a34a' }}>
            <FileSpreadsheet className="w-7 h-7" />
          </div>
          <div>
            <h2 style={{ fontSize: '1.125rem', fontWeight: 800, color: '#0f172a', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              Daily Report Archive & Export Center
            </h2>
            <p style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '0.125rem' }}>
              Download today's reports or browse persistent historical Excel reports generated by the automated server background pipeline.
            </p>
          </div>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.75rem', fontFamily: 'monospace', color: '#16a34a', background: '#f0fdf4', padding: '0.5rem 0.75rem', borderRadius: '8px', border: '1px solid #bbf7d0' }}>
          <CheckCircle2 className="w-4 h-4" style={{ color: '#16a34a' }} />
          <span>Persistent Storage Active</span>
        </div>
      </div>

      {/* TODAY'S EXCEL DOWNLOAD CARDS */}
      <div>
        <h3 style={{ fontSize: '0.75rem', fontWeight: 800, color: '#334155', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <Sparkles className="w-4 h-4" style={{ color: '#d97706' }} /> TODAY'S REPORTS ({todayStr})
        </h3>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '1rem' }}>
          {/* 1. STARTUPS EXCEL */}
          <div className="zyoin-card" style={{ padding: '1.25rem', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', borderTop: '4px solid #7e22ce' }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                <Rocket className="w-5 h-5" style={{ color: '#7e22ce' }} />
                <span style={{ fontSize: '10px', fontFamily: 'monospace', color: '#94a3b8', textTransform: 'uppercase' }}>Startups</span>
              </div>
              <h4 style={{ fontSize: '0.9375rem', fontWeight: 700, color: '#0f172a' }}>Zyoin Startups Report</h4>
              <p style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '0.25rem' }}>28 mandatory columns including evidence URLs, BD pitch angles & TA contact roles.</p>
            </div>

            <button
              onClick={() => handleDownload(`/api/reports/download/${todayStr}/startups`)}
              className="btn-zyoin-primary"
              style={{ marginTop: '1rem', width: '100%', justifyContent: 'center', fontSize: '0.75rem' }}
            >
              <Download className="w-4 h-4" /> Download Startups XLSX
            </button>
          </div>

          {/* 2. GCC EXCEL */}
          <div className="zyoin-card" style={{ padding: '1.25rem', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', borderTop: '4px solid #16a34a' }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                <Globe2 className="w-5 h-5" style={{ color: '#16a34a' }} />
                <span style={{ fontSize: '10px', fontFamily: 'monospace', color: '#94a3b8', textTransform: 'uppercase' }}>GCC</span>
              </div>
              <h4 style={{ fontSize: '0.9375rem', fontWeight: 700, color: '#0f172a' }}>Zyoin GCC Report</h4>
              <p style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '0.25rem' }}>34 columns including parent MNC, campus establishment details & expansion evidence.</p>
            </div>

            <button
              onClick={() => handleDownload(`/api/reports/download/${todayStr}/gcc`)}
              style={{ marginTop: '1rem', width: '100%', justifyContent: 'center', fontSize: '0.75rem', background: '#16a34a', color: '#fff', fontWeight: 600, padding: '0.6rem 1.2rem', borderRadius: '8px', border: 'none', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: '0.5rem' }}
            >
              <Download className="w-4 h-4" /> Download GCC XLSX
            </button>
          </div>

          {/* 3. MANAGER SUMMARY EXCEL */}
          <div className="zyoin-card" style={{ padding: '1.25rem', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', borderTop: '4px solid #d97706' }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                <Sparkles className="w-5 h-5" style={{ color: '#d97706' }} />
                <span style={{ fontSize: '10px', fontFamily: 'monospace', color: '#94a3b8', textTransform: 'uppercase' }}>Executive</span>
              </div>
              <h4 style={{ fontSize: '0.9375rem', fontWeight: 700, color: '#0f172a' }}>Daily Manager Summary</h4>
              <p style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '0.25rem' }}>Executive research overview stats + Top 10 target prospects breakdown.</p>
            </div>

            <button
              onClick={() => handleDownload(`/api/reports/download/${todayStr}/summary`)}
              style={{ marginTop: '1rem', width: '100%', justifyContent: 'center', fontSize: '0.75rem', background: '#d97706', color: '#fff', fontWeight: 600, padding: '0.6rem 1.2rem', borderRadius: '8px', border: 'none', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: '0.5rem' }}
            >
              <Download className="w-4 h-4" /> Download Summary XLSX
            </button>
          </div>

          {/* 4. REJECTED EXCLUSIONS EXCEL */}
          <div className="zyoin-card" style={{ padding: '1.25rem', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', borderTop: '4px solid #dc2626' }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                <ShieldAlert className="w-5 h-5" style={{ color: '#dc2626' }} />
                <span style={{ fontSize: '10px', fontFamily: 'monospace', color: '#94a3b8', textTransform: 'uppercase' }}>Exclusions</span>
              </div>
              <h4 style={{ fontSize: '0.9375rem', fontWeight: 700, color: '#0f172a' }}>Rejected Companies Report</h4>
              <p style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '0.25rem' }}>Audit log showing excluded existing Zyoin clients and low-score rejections.</p>
            </div>

            <button
              onClick={() => handleDownload(`/api/reports/download/${todayStr}/exclusions`)}
              className="btn-zyoin-secondary"
              style={{ marginTop: '1rem', width: '100%', justifyContent: 'center', fontSize: '0.75rem' }}
            >
              <Download className="w-4 h-4" /> Download Exclusions XLSX
            </button>
          </div>
        </div>
      </div>

      {/* HISTORICAL REPORT ARCHIVE LIST */}
      <div className="zyoin-card" style={{ padding: '1.25rem' }}>
        <h3 style={{ fontSize: '0.75rem', fontWeight: 800, color: '#334155', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <FolderArchive className="w-4 h-4" style={{ color: '#7e22ce' }} /> HISTORICAL REPORT ARCHIVE BY DATE
        </h3>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          {archive.map((item) => (
            <div
              key={item.date}
              style={{ padding: '1rem', borderRadius: '12px', background: '#f8fafc', border: '1px solid #e2e8f0', display: 'flex', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between', gap: '1rem' }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                <div style={{ padding: '0.75rem', borderRadius: '8px', background: '#f3e8ff', color: '#7e22ce', fontFamily: 'monospace', textAlign: 'center', minWidth: '110px' }}>
                  <Calendar className="w-4 h-4" style={{ margin: '0 auto 0.125rem', color: '#7e22ce' }} />
                  <span style={{ fontSize: '0.75rem', fontWeight: 700 }}>{item.date}</span>
                </div>
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <span style={{ fontSize: '0.875rem', fontWeight: 700, color: '#0f172a' }}>{item.finalLeadsCount} Qualified Leads</span>
                    <span style={{ fontSize: '0.75rem', color: '#7e22ce' }}>({item.startupsCount} Startups, {item.gccCount} GCCs)</span>
                  </div>
                  <p style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '0.125rem' }}>
                    Completed at: <span style={{ fontFamily: 'monospace', color: '#334155' }}>{item.completedAt}</span> | HOT: <strong style={{ color: '#dc2626' }}>{item.hotLeadsCount}</strong>, HIGH: <strong style={{ color: '#d97706' }}>{item.highLeadsCount}</strong>
                  </p>
                </div>
              </div>

              {/* Download Buttons for this date */}
              <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '0.5rem' }}>
                <button
                  onClick={() => handleDownload(`/api/reports/download/${item.date}/startups`)}
                  style={{ padding: '0.375rem 0.625rem', borderRadius: '8px', background: '#f3e8ff', border: '1px solid #e9d5ff', color: '#7e22ce', fontSize: '0.75rem', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '0.25rem', cursor: 'pointer' }}
                >
                  <Download className="w-3.5 h-3.5" /> Startups
                </button>
                <button
                  onClick={() => handleDownload(`/api/reports/download/${item.date}/gcc`)}
                  style={{ padding: '0.375rem 0.625rem', borderRadius: '8px', background: '#f0fdf4', border: '1px solid #bbf7d0', color: '#15803d', fontSize: '0.75rem', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '0.25rem', cursor: 'pointer' }}
                >
                  <Download className="w-3.5 h-3.5" /> GCC
                </button>
                <button
                  onClick={() => handleDownload(`/api/reports/download/${item.date}/summary`)}
                  style={{ padding: '0.375rem 0.625rem', borderRadius: '8px', background: '#fffbeb', border: '1px solid #fef3c7', color: '#d97706', fontSize: '0.75rem', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '0.25rem', cursor: 'pointer' }}
                >
                  <Download className="w-3.5 h-3.5" /> Summary
                </button>
                <button
                  onClick={() => handleDownload(`/api/reports/download/${item.date}/exclusions`)}
                  style={{ padding: '0.375rem 0.625rem', borderRadius: '8px', background: '#fef2f2', border: '1px solid #fecaca', color: '#dc2626', fontSize: '0.75rem', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '0.25rem', cursor: 'pointer' }}
                >
                  <Download className="w-3.5 h-3.5" /> Exclusions
                </button>
              </div>
            </div>
          ))}

          {archive.length === 0 && !loading && (
            <div style={{ padding: '2rem', textAlign: 'center', color: '#94a3b8', fontSize: '0.75rem' }}>
              No historical report archives found yet. Today's report will be archived upon completion.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
